package structs

import (
	"encoding/json"

	errors2 "github.com/lusantisuper/api-rede-golang/apierr"
	"github.com/lusantisuper/api-rede-golang/utils"
)

// Request Struct of the request to de REDE's API
type Request struct {
	// Optional: Define true if you want the request to be automatic captured
	Capture bool `json:"Capture"`
	// Optional: Payment method -> "credit" and "debit"
	Kind string `json:"Kind"`
	// Task code generated by the establishment
	Reference string `json:"Reference"`
	// Price of the product R$10,00 = 1000
	Amount int `json:"Amount"`
	// Optional: Number of payments in installments -> 2 until 12
	// Not setting this value make the one time pay
	Installments int `json:"Installments"`
	// Optional: Name for the card's owner
	CardHolderName string `json:"CardHolderName"`
	// Card's number
	CardNumber int `json:"CardNumber"`
	// Expiration month -> 1 until 12
	ExpirationMonth int `json:"ExpirationMonth"`
	// Expiration year -> could be 2021 or 21
	ExpirationYear int `json:"ExpirationYear"`
	// Optional: Card's security code
	SecurityCode int `json:"SecurityCode"`
	// Optional: This string will be printed on the bill
	SoftDescriptor string `json:"SoftDescriptor"`
	// Optional: Is it a subscription? This is only a log, the payment need to be redone every time the store wants
	Subscription bool `json:"Subscription"`
	// TODO
	origin int
	// PV number
	DistributorAffiliation int `json:"DistributorAffiliation"`
	// TODO
	brandTid string
}

type request struct {
	// Optional: Define true if you want the request to be automatic captured
	capture bool
	// Optional: Payment method -> "credit" and "debit"
	kind string
	// Task code generated by the establishment
	reference string
	// Price of the product R$10,00 = 1000
	amount int
	// Optional: Number of payments in installments -> 2 until 12
	// Not setting this value make the one time pay
	installments int
	// Optional: Name for the card's owner
	cardHolderName string
	// Card's number
	cardNumber int
	// Expiration month -> 1 until 12
	expirationMonth int
	// Expiration year -> could be 2021 or 21
	expirationYear int
	// Optional: Card's security code
	securityCode int
	// Optional: This string will be printed on the bill
	softDescriptor string
	// Optional: Is it a subscription? This is only a log, the payment need to be redone every time the store wants
	subscription bool
	// TODO
	origin int
	// PV number
	distributorAffiliation int
	// TODO
	brandTid string
}

// ToJSON Return a valid byte array of the request
func (r Request) ToJSON() ([]byte, error) {
	result := request{
		capture:                r.Capture,
		kind:                   r.Kind,
		reference:              r.Reference,
		amount:                 r.Amount,
		installments:           r.Installments,
		cardHolderName:         r.CardHolderName,
		cardNumber:             r.CardNumber,
		expirationMonth:        r.ExpirationMonth,
		expirationYear:         r.ExpirationYear,
		securityCode:           r.SecurityCode,
		softDescriptor:         r.SoftDescriptor,
		subscription:           r.Subscription,
		origin:                 r.origin,
		distributorAffiliation: r.DistributorAffiliation,
		brandTid:               r.brandTid,
	}

	// Adding all necessary parameters
	if utils.IsStringEmpty(r.Reference) {
		return nil, errors2.APIErr(errors2.INSUFFICIENTPARAMETERS)
	}
	if r.Amount < 0 || r.Amount > 1000000000 {
		return nil, errors2.APIErr(errors2.WRONGAMOUNT)
	}
	if r.CardNumber == 0 {
		return nil, errors2.APIErr(errors2.INSUFFICIENTPARAMETERS)
	}
	if r.ExpirationMonth < 0 || r.ExpirationMonth > 12 {
		return nil, errors2.APIErr(errors2.WRONGDATENUMBER)
	}
	if r.ExpirationYear < 20 || r.ExpirationYear > 60 {
		return nil, errors2.APIErr(errors2.WRONGDATENUMBER)
	}
	if r.DistributorAffiliation == 0 {
		return nil, errors2.APIErr(errors2.INSUFFICIENTPARAMETERS)
	}

	// Adding all optional parameters
	if !r.Capture {
		result.capture = false
	}
	if !utils.IsStringEmpty(r.Kind) {
		result.kind = r.Kind
	}
	if r.Installments >= 2 && r.Installments <= 12 {
		result.installments = r.Installments
	} else {
		result.installments = 1
	}
	if !utils.IsStringEmpty(r.CardHolderName) {
		result.cardHolderName = r.CardHolderName
	}
	if !utils.IsStringEmpty(r.SoftDescriptor) {
		result.softDescriptor = r.SoftDescriptor
	}

	jsonResult, err := json.Marshal(result)
	return jsonResult, err
}
